---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3032
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      securityContext:
        runAsUser: 999
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:v0.3.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        - name: EXPORTER_TYPE
          value: "msteams"
        - name: MSTEAMS_URL
          value: "https://outlook.office.com/webhook/754e1a15-9986-4c07-b8c3-92a191c5408e@85c997b9-f494-46b3-a11d-772983cf6f11/IncomingWebhook/b4d0752c4e1044c194a16dec59346e1a/94b19806-37d5-4427-bed0-abade65d377b"        
        - name: LISTEN_ADDRESS
          value: ":3032"
